# Generated by Django 4.2.8 on 2025-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_actor_i_dcd783_idx',
            old_name='apps_audit_actor_7ff847_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action_e33994_idx',
            old_name='apps_audit_action_bf110a_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_user', 'Crear usuario'), ('update_profile', 'Actualizar perfil'), ('change_password', 'Cambiar contraseña'), ('set_role', 'Cambiar rol'), ('delete_user', 'Eliminar usuario'), ('reset_password', 'Resetear contraseña'), ('create_client', 'Crear cliente'), ('update_client', 'Actualizar cliente'), ('delete_client', 'Eliminar cliente')], max_length=50),
        ),
    ]
