# Generated by Django 4.2.8 on 2025-12-11 15:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota de cliente',
                'verbose_name_plural': 'Notas de cliente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_last_na_392efd_idx',
            old_name='clients_cli_last_na_472c33_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_company_9dfa94_idx',
            old_name='clients_cli_company_713ae6_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='clients_cli_cuit_84d1e1_idx',
            old_name='clients_cli_cuit_d6a3e5_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='coholder',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='coholder',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client'),
        ),
    ]
