# Generated by Django 4.2.8 on 2025-12-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='employment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empleo / Ocupación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='marital_status',
            field=models.CharField(choices=[('casado', 'Casado'), ('soltero', 'Soltero'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=10, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
        migrations.AlterField(
            model_name='coholder',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='Nacionalidad'),
        ),
    ]
