# Generated by Django 4.2.8 on 2025-12-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_employment_alter_client_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coholder',
            name='employment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empleo / Ocupación'),
        ),
    ]
