# Generated by Django 4.2.8 on 2025-12-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_coholder_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coholder',
            name='doc_type',
            field=models.CharField(choices=[('LE', 'Libreta de Enrolamiento (LE)'), ('LC', 'Libreta Cívica (LC)'), ('DNI', 'DNI'), ('PAS', 'Pasaporte')], default='DNI', max_length=3, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='doc_type',
            field=models.CharField(choices=[('LE', 'Libreta de Enrolamiento (LE)'), ('LC', 'Libreta Cívica (LC)'), ('DNI', 'DNI'), ('PAS', 'Pasaporte')], max_length=3, verbose_name='Tipo de Documento'),
        ),
    ]
