# Generated by Django 4.2.8 on 2025-12-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_coholder_doc_type_alter_client_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Notas')),
                ('starts_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client')),
            ],
            options={
                'verbose_name': 'Evento de cliente',
                'verbose_name_plural': 'Eventos de cliente',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['starts_at'], name='clients_cli_starts__1458f4_idx')],
            },
        ),
    ]
