# Generated by Django 4.2.8 on 2025-12-14 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_clientevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
