# Generated by Django 4.2.8 on 2025-12-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0009_client_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead de cliente',
                'verbose_name_plural': 'Leads de cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
