# Generated by Django 4.2.8 on 2025-12-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0010_clientlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlead',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fuente (publicidad)'),
        ),
        migrations.CreateModel(
            name='LeadInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='clients.clientlead')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrevista de lead',
                'verbose_name_plural': 'Entrevistas de lead',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientLeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.clientlead')),
            ],
            options={
                'verbose_name': 'Nota de lead',
                'verbose_name_plural': 'Notas de lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
