# Generated by Django 4.2.8 on 2025-12-17 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientlead_source_leadinterview_clientleadnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevent',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client'),
        ),
    ]
