# Generated by Django 4.2.8 on 2025-12-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientevent_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cliente rápido', 'verbose_name_plural': 'Clientes rápidos'},
        ),
        migrations.AlterModelOptions(
            name='clientleadnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nota de cliente rápido', 'verbose_name_plural': 'Notas de cliente rápido'},
        ),
        migrations.AddField(
            model_name='clientevent',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clients.clientlead'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='lead_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre lead'),
        ),
        migrations.AddField(
            model_name='clientevent',
            name='lead_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono lead'),
        ),
    ]
